name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: window-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v2
      - name: say hi to Vova
        run: echo "hello Vova"